### PR TITLE
fix: eslint and persistent cache compatibility

### LINKED ISSUE #63: Eslint doesn't consistently report errors with persistent cache
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

When cache is persisted to disk, `@roots/bud-eslint` inconsistently reports errors.

## Steps to reproduce

1. Install `@roots/bud-eslint`
2. Call `bud.persist()`
3. Run a build with a JS syntax error

**Expected behavior:**

- Errors are reported to console

**Actual behavior:**

- Errors are reported initially
- Subsequent rebuilds are emitted (with errors) and nothing is reported

**Reproduces how often:** 

100%

## Versions

4.1.0

### PR DESCRIPTION
**Pull request by kellymears**
## Type of change

- MINOR: feature

## Dependencies added

- [eslint-plugin-prettier](https://npmjs.com/eslint-plugin-prettier)

## Issues fixed

- Fixes #63 

## Details

This fixes compatibility between @roots/bud-eslint and @roots/bud-cache. 

It works by submitting the eslint generated cache artifact to the array of files used by webpack for cache validation (it actually adds all files in the root of `storage/cache` directory since I suspect but have not confirmed this will also effect `@roots/bud-stylelint`). 

Additionally, bud uses this eslint cache artifact to the array of files used by `bud.cache.version()` to generate the cache md4.

It also adds a configuration utility for easier adjustment of options: `bud.eslint`. Configuration can be adjusted with `bud.eslint.config()`.

### CODE REVIEW

File: packages/@roots/bud-api/src/methods/persist.ts [hunk 1]
```diff
@@ -27,51 +26,33 @@ declare module '@roots/bud-framework' {
...
+        ),
+        buildDependencies: this.hooks.filter(
+          'build/cache/buildDependencies',
+        ),
+      }))
 
-        /**
-         * Individual settings
-         */
-        .hooks.on('build/cache/name', () => this.cache.cacheName)
```
Comment (kellymears) [inline packages/@roots/bud-api/src/methods/persist.ts:56]: I don't think we need to name our cache since we are supplying a version so I removed this.

File: packages/@roots/bud-api/src/methods/persist.ts [hunk 2]
```diff
@@ -27,51 +26,33 @@ declare module '@roots/bud-framework' {
...
-        .hooks.on(
-          'build/cache/version',
-          () => this.cache.version,
-        )
-        .hooks.on('build/cache/type', () => 'filesystem')
-        .hooks.on('build/cache/cacheDirectory', () =>
-          this.path('storage'),
-        )
-        .hooks.on('build/cache/cacheLocation', () =>
```
Comment (kellymears) [inline packages/@roots/bud-api/src/methods/persist.ts:65]: Letting webpack handle this internally for a similar reason https://github.com/roots/bud/pull/64/files#r637445882

File: packages/@roots/bud-build/src/Build/config.ts [hunk 3]
```diff
@@ -52,18 +52,11 @@ export function config(this: Framework): void {
...
-    .hooks.on('build/cache/type', () => 'memory')
-    .hooks.on('build/cache/cacheDirectory', () => undefined)
-    .hooks.on('build/cache/cacheLocation', () => undefined)
-    .hooks.on('build/cache/buildDependencies', undefined)
-    .hooks.on('build/cache/managedPaths', () => undefined)
     .hooks.on('build/experiments', () => ({
       lazyCompilation: false,
     }))
     .hooks.on('build/infrastructureLogging', () => ({
-      level: 'none',
```
Comment (kellymears) [inline packages/@roots/bud-build/src/Build/config.ts:66]: I wasn't certain about whether or not `infrastructureLogging` being explicitly disabled might be implicated by this issue. If it works with `level: none` I would still prefer it for speed improvements. But I don't know enough about this api to feel comfortable.

To prevent `infrastructureLogging` from clogging the console I pass it the bud logging instance. Haven't confirmed if this actually works but it does prevent console output and that's all I really care about right now.

File: packages/@roots/bud-cache/src/index.ts [hunk 4]
```diff
@@ -53,14 +56,20 @@ class Cache extends Service implements Base {
       ...this.app.discovery.resolveFrom.map(
         dep => `${dep}/lib/cjs/index.js`,
       ),
+      ...this.app.discovery.resolveFrom.map(
+        dep => `${dep}/package.json`,
+      ),
+      ...this.cacheFiles,
+      this.app.path('storage', 'cache/*'),
```
Comment (kellymears) [inline packages/@roots/bud-cache/src/index.ts:63]: I think this is the clutch bit.

File: packages/@roots/bud-dashboard/src/Dashboard/Dashboard.tsx [hunk 5]
```diff
@@ -30,11 +30,11 @@ const Dashboard: Dashboard.Component = ({bud}) => {
...
   return (
     <Box flexDirection="column">
-      {appProps.hasErrors && appProps.errors?.length > 0 && (
+      {appProps.errors?.length > 0 && (
         <Static marginBottom={1} items={appProps.errors}>
-          {(err: Dashboard.Compilation.WebpackMessage) => (
+          {(err: Dashboard.Compilation.WebpackMessage, id) => (
             <Module
-              key={err.moduleIdentifier}
+              key={`${id}-webpack-error`}
```
Comment (kellymears) [inline packages/@roots/bud-dashboard/src/Dashboard/Dashboard.tsx:37]: the default eslint formatter doesn't actually pass a message object the way native webpack messages work (there is no `moduleIdentifier`, or its empty).

File: packages/@roots/bud-dashboard/src/hooks/useCompilation.ts [hunk 6]
```diff
@@ -62,14 +58,13 @@ export const useCompilation: Dashboard.Compilation.Hook = app => {
...
 
-    app.isProduction &&
-      app.compiler.instance.hooks.done.tap(app.name, () =>
-        app.compiler.instance.close(err => {
-          err && setErrors([err])
-          setClosed(true)
-          setTimeout(process.exit, 2000)
-        }),
-      )
+    app.compiler.instance.hooks.done.tap(app.name, () =>
```
Comment (kellymears) [inline packages/@roots/bud-dashboard/src/hooks/useCompilation.ts:61]: This is kind of unrelated tbh, but an important fix for dev build caching.

We want the `close` fn to be called by dev (so that cache is consistently written).. but we don't want the process to be closed. The way it was before skipped the whole call, which isn't what we want.

File: packages/@roots/bud-eslint/src/index.ts [hunk 7]
```diff
@@ -1,18 +1,34 @@
 import {Extension} from './interface'
 import EslintPlugin from 'eslint-webpack-plugin'
+import {Eslint} from './api'
 
 const extension: Extension = {
   name: 'eslint-webpack-plugin',
 
-  options: ({path}) => ({
+  register: ({cache, path}) => {
```
Comment (kellymears) [inline packages/@roots/bud-eslint/src/index.ts:8]: this might be unnecessary.
